<?php
return array (
  'admin' => 
  array (
    'module' => 'admin',
    'name' => 'admin',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'admin_email\' => \'phpcms@phpcms.cn\',
  \'maxloginfailedtimes\' => \'8\',
  \'minrefreshtime\' => \'2\',
  \'mail_type\' => \'1\',
  \'mail_server\' => \'mail.ukcnetpa.org\',
  \'mail_port\' => \'26\',
  \'category_ajax\' => \'0\',
  \'mail_user\' => \'info@ukcnetpa.org\',
  \'mail_auth\' => \'1\',
  \'mail_from\' => \'info@ukcnetpa.org\',
  \'mail_password\' => \'Good2014\',
  \'errorlog_size\' => \'20\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-18',
    'updatedate' => '2010-10-18',
  ),
  'member' => 
  array (
    'module' => 'member',
    'name' => '会员',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'allowregister\' => \'1\',
  \'choosemodel\' => \'1\',
  \'enablemailcheck\' => \'0\',
  \'enablcodecheck\' => \'0\',
  \'mobile_checktype\' => \'0\',
  \'user_sendsms_title\' => \'\',
  \'registerverify\' => \'1\',
  \'showapppoint\' => \'0\',
  \'rmb_point_rate\' => \'10\',
  \'defualtpoint\' => \'0\',
  \'defualtamount\' => \'0\',
  \'showregprotocol\' => \'1\',
  \'regprotocol\' => \'欢迎你申请注册成为英中协会会员

1.请仔细阅读网站的会员制度和公司章程。
2.我们会审核你的申请，如有需要我们会联系你。
3.一般可能需要5个工作日的时间。
4.一旦你的申请通过，我们会发送邮件给你。
\',
  \'registerverifymessage\' => \' 欢迎您注册成英中经贸交流促进会用户，您的账号需要邮箱认证，点击下面链接进行认证：{click}
或者将网址复制到浏览器：{url}\',
  \'forgetpassword\' => \'密码找回，请在一小时内点击下面链接进行操作：{click}
或者将网址复制到浏览器：{url}\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'pay' => 
  array (
    'module' => 'pay',
    'name' => '支付',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'digg' => 
  array (
    'module' => 'digg',
    'name' => '顶一下',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'special' => 
  array (
    'module' => 'special',
    'name' => '专题',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'content' => 
  array (
    'module' => 'content',
    'name' => '内容模块',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'search' => 
  array (
    'module' => 'search',
    'name' => '全站搜索',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'fulltextenble\' => \'1\',
  \'relationenble\' => \'1\',
  \'suggestenable\' => \'1\',
  \'sphinxenable\' => \'0\',
  \'sphinxhost\' => \'10.228.134.102\',
  \'sphinxport\' => \'9312\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'scan' => 
  array (
    'module' => 'scan',
    'name' => '木马扫描',
    'url' => 'scan',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'attachment' => 
  array (
    'module' => 'attachment',
    'name' => '附件',
    'url' => 'attachment',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'block' => 
  array (
    'module' => 'block',
    'name' => '碎片',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'collection' => 
  array (
    'module' => 'collection',
    'name' => '采集模块',
    'url' => 'collection',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'dbsource' => 
  array (
    'module' => 'dbsource',
    'name' => '数据源',
    'url' => '',
    'iscore' => '1',
    'version' => '',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'template' => 
  array (
    'module' => 'template',
    'name' => '模板风格',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'release' => 
  array (
    'module' => 'release',
    'name' => '发布点',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'cnzz' => 
  array (
    'module' => 'cnzz',
    'name' => 'CNZZ统计',
    'url' => 'cnzz/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'CNZZ统计',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-15',
    'updatedate' => '2010-09-15',
  ),
  'video' => 
  array (
    'module' => 'video',
    'name' => '视频库',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-09-28',
    'updatedate' => '2012-09-28',
  ),
  'announce' => 
  array (
    'module' => 'announce',
    'name' => '公告',
    'url' => 'announce/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '公告',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'comment' => 
  array (
    'module' => 'comment',
    'name' => '评论',
    'url' => 'comment/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '评论',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'link' => 
  array (
    'module' => 'link',
    'name' => '友情链接',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'vote' => 
  array (
    'module' => 'vote',
    'name' => '投票',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'default_style\' => \'default\',
    \'vote_tp_template\' => \'vote_tp\',
    \'allowguest\' => \'1\',
    \'enabled\' => \'1\',
    \'interval\' => \'1\',
    \'credit\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'message' => 
  array (
    'module' => 'message',
    'name' => '短消息',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'mood' => 
  array (
    'module' => 'mood',
    'name' => '新闻心情',
    'url' => 'mood/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '新闻心情',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'poster' => 
  array (
    'module' => 'poster',
    'name' => '广告模块',
    'url' => 'poster/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '广告模块',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'formguide' => 
  array (
    'module' => 'formguide',
    'name' => '表单向导',
    'url' => 'formguide/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'formguide',
    'setting' => 'array (
  \'allowmultisubmit\' => \'1\',
  \'interval\' => \'30\',
  \'allowunreg\' => \'0\',
  \'mailmessage\' => \'用户向我们提交了表单数据，赶快去看看吧。\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-20',
    'updatedate' => '2010-10-20',
  ),
  'wap' => 
  array (
    'module' => 'wap',
    'name' => '手机门户',
    'url' => 'wap/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '手机门户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'upgrade' => 
  array (
    'module' => 'upgrade',
    'name' => '在线升级',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-05-18',
    'updatedate' => '2011-05-18',
  ),
  'tag' => 
  array (
    'module' => 'tag',
    'name' => '标签向导',
    'url' => 'tag/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '标签向导',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2013-11-22',
    'updatedate' => '2013-11-22',
  ),
  'sms' => 
  array (
    'module' => 'sms',
    'name' => '短信平台',
    'url' => 'sms/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '短信平台',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-09-02',
    'updatedate' => '2011-09-02',
  ),
  'guestbook' => 
  array (
    'module' => 'guestbook',
    'name' => '',
    'url' => '',
    'iscore' => '0',
    'version' => '2.0beta',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-03-02',
    'updatedate' => '2010-04-10',
  ),
);
?>